BEGIN;

CREATE TEMP TABLE constraint_lab (
    item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name text NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    sku text NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true
);

INSERT INTO constraint_lab (item_name, quantity, unit_price, sku)
VALUES ('Practice Item', 2, 1250.00, 'LAB-001');

SELECT item_id, item_name, quantity, unit_price, sku, is_active
FROM constraint_lab;

ROLLBACK;
